require 'testmite/ir'
require 'json'

EXAMPLE_FILE = 'spec/outputs/cucumber-ir.json'

describe Res::IR do

  context "Loading in IR files" do
    describe ".load" do
      it 'loads in a cucumber IR results file' do
        Res::IR.load( EXAMPLE_FILE )
      end
    end
  end

  context "Handling cucumber IR generated by Hive-Results gem" do
    
    let(:ir) { Res::IR.load( EXAMPLE_FILE ) }

    describe "#tests" do

      it 'returns an array of just the test portions of the json' do
        expect(ir.tests).to be_a Array
      end

      it 'only includes Scenarios and Scenario outline examples as tests' do
        node_types = ir.tests.collect { |t| t[:type] }.uniq!
        expect(node_types).to eq [ 'Cucumber::Scenario', 'Cucumber::ScenarioOutline::Example' ]
      end
      
    end
  end

end
