require 'spec_helper'
require 'res/ir'
require 'json'

EXAMPLE_FILE_JUNIT = 'spec/outputs/junit.res'

describe Res::IR do

  context "Loading in IR files" do
    describe ".load" do
      it 'loads in a Junit IR results file' do
        Res::IR.load( EXAMPLE_FILE_JUNIT )
      end
    end
  end

  context "Handling Junit IR generated by Hive-Results gem" do
    
    let(:ir) { Res::IR.load( EXAMPLE_FILE_JUNIT ) }

    describe "#tests" do

      it 'returns an array of just the test portions of the json' do
        expect(ir.tests).to be_a Array
        expect(ir.tests.count).to eq 7
      end

      it 'only includes Testcase as tests' do
        node_types = ir.tests.collect { |t| t[:type] }.uniq!
        expect(node_types).to eq [ 'JUnit::testcase' ]
      end
      
    end

    describe "#count" do
      it "Can pick out the passing tests from the run" do
        expect(ir.count(:passed)).to eq 6
      end

      it "Can pick out the failing tests from the run" do
        expect(ir.count(:failed)).to eq 1
      end

      it "Can identify there were no tests of an unknown type" do
        expect(ir.count(:unknown)).to eq 0
      end
    end
  end

end
